name: Update Recent Commits (Update Repo)
on:
  workflow_dispatch:

jobs:
  update-activity:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # 关键：赋予写入权限
    steps:
      - uses: actions/checkout@v4
      
      # 新增：配置Git提交者信息
      - name: Configure Git
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
      
      - name: Update Recent Commits
        uses: jamesgeorge007/github-activity-readme@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          GH_USERNAME: "xiaoran67"
          MAX_LINES: 5
          TARGET_FILE: "README.md"
